import { readFile } from "node:fs/promises";
import path from "node:path";
import { handleError, fail } from "@/lib/api";
import { prisma } from "@/lib/db";
import { EXPORT_DIR } from "@/lib/export";
import { resolveContext, TenantAccessError } from "@/lib/tenancy";

/**
 * GET /api/v1/exports/{id}/download
 *
 * Two things this route must never get wrong:
 *  1. Tenant scoping — the export is resolved through project -> client ->
 *     agency, so another agency's export id 404s.
 *  2. Path containment — even though the stored filename is generated by us,
 *     the path is re-verified to sit inside EXPORT_DIR before any read. A
 *     stored-path bug must not become arbitrary file disclosure.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { agencyId } = await resolveContext();
    const { id } = await params;

    const record = await prisma.export.findFirst({
      where: { id, project: { client: { agencyId } } },
      include: { project: true },
    });
    if (!record) throw new TenantAccessError();

    if (record.status !== "completed" || !record.filePath) {
      return fail("Export is not ready yet", 409);
    }

    const resolved = path.resolve(record.filePath);
    const root = path.resolve(EXPORT_DIR);
    if (resolved !== root && !resolved.startsWith(root + path.sep)) {
      return fail("Export path is outside the export directory", 400);
    }

    const file = await readFile(resolved).catch(() => null);
    if (!file) return fail("Export file is missing from storage", 410);

    await prisma.auditLog
      .create({
        data: {
          agencyId,
          projectId: record.projectId,
          action: "export.download",
          detail: JSON.stringify({
            exportId: record.id,
            format: record.format,
            rowCount: record.rowCount,
          }),
        },
      })
      .catch(() => null);

    const isXlsx = record.format === "xlsx";
    const safeName = `${record.project.name.replace(/[^\w.-]+/g, "-")}-keywords.${isXlsx ? "xlsx" : "csv"}`;

    return new Response(new Uint8Array(file), {
      headers: {
        "Content-Type": isXlsx
          ? "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          : "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeName}"`,
        "Content-Length": String(file.byteLength),
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    return handleError(error);
  }
}
